#!/usr/bin/env python3
"""Manually pull/start/update the production stack; no scheduler or auto rollback."""
import argparse
from _support import finish, installed_config, recovery_python
from athenaeum_ops.management import operate


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('command', choices=['pull', 'start', 'update'], help='start: empty first install; update: verified backup then pull/up')
    args = parser.parse_args()
    cfg = installed_config()
    recovery_python()
    operate(cfg, args.command)


if __name__ == '__main__':
    finish(main)
